name: Go Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: Set up dependencies
        run: |
          cd go/LinkedList/singly
          go mod tidy

      - name: Run tests
        run: |
          cd go/LinkedList/singly
          go test -v .
